"""\
Usage:
    mmc_ingest_entity_clusters <in:db> <in:tsv>

Arguments:
    <in:db>
        A path to a database generated by `mmc_ingest_mmcif`.  The entity 
        clusters will be added to this database.

    <in:tsv>
        A tab-separated file with two columns: The first should contain a 
        unique string for each cluster of "equivalent" entities.  The second 
        should contain an id number referencing one of the entities in the 
        database created by `mmc_ingest_models`.  The FASTA files created by 
        `mmc_extract_fasta` provide these id numbers as the name of each 
        sequence entry, so any clustering program that identifies sequences by 
        name will work.

        The MMseqs2 program generates TSV files in a suitable format for this 
        script.  It's possible that other clustering programs do, as well.
"""

import polars as pl
from .working_db import open_db, insert_entity_clusters

def main():
    from docopt import docopt
    args = docopt(__doc__)

    db = open_db(args['<in:db>'])
    clusters = pl.read_csv(
            source=args['<in:tsv>'],
            separator='\t',
            has_header=False,
            new_columns=['cluster', 'entity_id'],
    )

    insert_entity_clusters(db, clusters)
